# -*- coding: utf-8 -*-
"""DNNLab.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10z_k1YYgIx-GT13W9aHcWZoOafj-ZNDT

AIM: To create tensors and perform arithmetic operations using tensorflow.

---

TensorFlow is one of the famous deep learning framework, developed
by Google Team. It is a free and open source software library and designed
in Python programming language.
TensorFlow is completely based on Python. So, it is essential to have basic
knowledge of Python.
What is TensorFlow?
The word TensorFlow is made by two words, i.e., Tensor and Flow
1. Tensor is a multidimensional array
2. Flow is used to define the flow of data in operation.
TensorFlow is used to define the flow of data in operation on a multidimensional
array or Tensor.
"""

import tensorflow as tf

"""Tensor: A tensor is a vector or a matrix of n-dimensional that represents all type
of data. All values in a tensor hold similar data type with a known shape. The
shape of the data is the dimension of the matrix or an array. A tensor can be
generated from the input data or the result of a computation. In TensorFlow, all
operations are conducted inside a graph. The group is a set of calculation that takes
place successively. Each transaction is called an op node are connected.
"""

q1_decimal = tf.constant(1.12345, tf.float32,name='Decex')
print(q1_decimal)
q1_string = tf.constant("DYPIU", tf.string,name='Strex')
print(q1_string)
q2_boolean = tf.constant([True, True, False], tf.bool,name='Boolex')
print(q2_boolean)
q2_matrix = tf.constant([[1, 2], [3, 4]],tf.int32,name='2Dex')
print(q2_matrix)
q3_matrix = tf.constant([[[1, 2],[3, 4], [5, 6]]], tf.int32,name='3Dex')
print(q3_matrix)

"""Each tensor object is generated
with
a unique label (name),
a dimension (shape)
a data type (dtype).


Shape of tensor

When we print the tensor, TensorFlow guesses the shape. However, we can get the shape property.
Below, we construct a matrix filled with a number from 10 to 15 and we check the shape of m_shape
"""

m= tf.constant([[11,10],[13,12,],[15,14]])
mshape= tf.shape(m)
print(mshape)

"""Performing Arithmetic Operations


---


Addition, Multiplication, Divide, Subtract, Power, Exponential, Square Root

Here, we took 'matrix_1' and 'matrix_2' common matrices for basic arithmetic Operations
We created 'matrix_3' for Exponential and Square-root operation.
"""

a=tf.constant([3,4], dtype=tf.int32)
b=tf.constant([[1,2]], dtype=tf.int32)
x=tf.constant([2.0], dtype=tf.float32)
print(tf.sqrt(x))
print(tf.exp(x))
print(tf.add(a,b))
print(tf.subtract(a,b))
print(tf.multiply(a,b))
print(tf.divide(a,b))
print(tf.pow(a,b))

"""Name: Sanket Kumar Choudhary

PRN: 20190802137
"""